UOM = (
        ('BG', 'Bag'),
        ('BF', 'Board Fleet'),
        ('LT', 'Lot'),
        ('LY', 'Linear Yard'),
        ('BL', 'Bale'),
        ('M', 'Thousand'),
        ('BT', 'Bottle'),
        ('MG', 'Milligram'),
        ('BX', 'Box'),
        ('ML', 'Milliliter'),
        ('C', 'Hundred'),
        ('MM', 'Millimeter'),
        ('CC', 'Cubic Centimeter'),
        ('MN', 'Minute'),
        ('CF', 'Cubic Feet'),
        ('MO', 'Month'),
        ('CI', 'Curie'),
        ('MR', 'Micron'),
        ('CL', 'Cylinder'),
        ('MT', 'Meter'),
        ('CM', 'Centimeter'),
        ('OG', 'Omega'),
        ('CN', 'Can'),
        ('OZ', 'Ounce'),
        ('CS', 'Case'),
        ('PA', 'Package'),
        ('CT', 'Carton'),
        ('PC', 'Piece'),
        ('CW', 'Hundred Weight'),
        ('PG', 'Page'),
        ('CY', 'Cubic Yard'),
        ('PK', 'Pack'),
        ('DI', 'Diameter'),
        ('PL', 'Pail'),
        ('DR', 'Drum'),
        ('PR', 'Pair'),
        ('DW', 'Dewar'),
        ('PT', 'Pint'),
        ('DY', 'Day'),
        ('QR', 'Quarter'),
        ('DZ', 'Dozen'),
        ('QT', 'Quart'),
        ('EA', 'Each'),
        ('RD', 'Rod'),
        ('FT', 'Feet'),
        ('RL', 'Roll'),
        ('GL', 'Gallon'),
        ('RM', 'Ream'),
        ('GM', 'Gram'),
        ('SF', 'Square Feet'),
        ('GN', 'Grain'),
        ('SH', 'Sheet'),
        ('GR', 'Gross'),
        ('ST', 'Set'),
        ('HR', 'Hour'),
        ('SY', 'Square Yard'),
        ('IN', 'Inch'),
        ('TB', 'Tube'),
        ('JR', 'Jar'),
        ('TR', 'Transaction'),
        ('KG', 'Kilogram'),
        ('UT', 'Unit'),
        ('KT', 'Kit'),
        ('VL', 'Vial'),
        ('LA', 'Lambda'),
        ('WK', 'Week'),
        ('LB', 'Pound'),
        ('YD', 'Yard'),
        ('LF', 'Linear Feet'),
        ('YR', 'Year'),
        ('LG', 'Length'),
        ('LI', 'Liter')
       )

