# Generated by Django 4.0.3 on 2022-03-30 04:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stock_delete_stockcreate'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_entry_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Stock created at:'),
            preserve_default=False,
        ),
    ]
