# Generated by Django 4.0.3 on 2022-03-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stock_stock_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='UoM',
            field=models.CharField(choices=[('Bag', 'Bag'), ('BKT', 'Bucket')], default=1, max_length=250),
            preserve_default=False,
        ),
    ]
